// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: gateway.proto
package gateway

import (
	"context"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// GatewayServiceName is the fully-qualified name of the GatewayService service.
	GatewayServiceName = "gateway.GatewayService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GatewayServiceGetInfoProcedure is the fully-qualified name of the GatewayService's GetInfo RPC.
	GatewayServiceGetInfoProcedure = "/gateway.GatewayService/GetInfo"
)

var (
	_ GatewayService = (*GatewayServiceImpl)(nil)
)

// GatewayService is a client for the gateway.GatewayService service.
type GatewayService interface {
	GetInfo(ctx context.Context, req *GetInfoRequest, opts ...client.CallOption) (*GetInfoResponse, error)
}

// NewGatewayService constructs a client for the gateway.GatewayService service.
func NewGatewayService(cli *client.Client, opts ...client.ReferenceOption) (GatewayService, error) {
	conn, err := cli.DialWithInfo("gateway.GatewayService", &GatewayService_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &GatewayServiceImpl{
		conn: conn,
	}, nil
}

func SetConsumerGatewayService(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &GatewayService_ClientInfo)
}

// GatewayServiceImpl implements GatewayService.
type GatewayServiceImpl struct {
	conn *client.Connection
}

func (c *GatewayServiceImpl) GetInfo(ctx context.Context, req *GetInfoRequest, opts ...client.CallOption) (*GetInfoResponse, error) {
	resp := new(GetInfoResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "GetInfo", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

var GatewayService_ClientInfo = client.ClientInfo{
	InterfaceName: "gateway.GatewayService",
	MethodNames:   []string{"GetInfo"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*GatewayServiceImpl)
		dubboCli.conn = conn
	},
}

// GatewayServiceHandler is an implementation of the gateway.GatewayService service.
type GatewayServiceHandler interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
}

func RegisterGatewayServiceHandler(srv *server.Server, hdlr GatewayServiceHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &GatewayService_ServiceInfo, opts...)
}

func SetProviderGatewayService(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &GatewayService_ServiceInfo)
}

var GatewayService_ServiceInfo = server.ServiceInfo{
	InterfaceName: "gateway.GatewayService",
	ServiceType:   (*GatewayServiceHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "GetInfo",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(GetInfoRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*GetInfoRequest)
				res, err := handler.(GatewayServiceHandler).GetInfo(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
